# Refer https://github.com/zyrouge/pong#configuration for documentation

urls:
    - path: "https://hst.ujol.dev"
      type: "get"
    - path: "https://reddviz.deno.dev/gimme"
      type: "get"
    - path: "https://reddviz.amar.kim/gimme"
      type: "get"
    - path: "https://dumb.onrender.com"
      type: "get"
