# Refer https://github.com/zyrouge/pong#configuration for documentation

urls:
    - path: "https://hst.aytea.ga"
      type: "get"
    - path: "https://memeapi.cyclic.app/gimme"
      type: "get"
    - path: "https://memeapi.cyclic.app"
      type: "get"
    - path: "https://klik.ml/health"
      type: "get"
    - path: "https://dumb.onrender.com"
      type: "get"
