# Refer https://github.com/zyrouge/pong#configuration for documentation

urls:
    - path: "https://shrt.ml"
      type: "get"
    - path: "https://api.aytea.ml"
      type: "get"
    - path: "https://memeapi.up.railway.app"
      type: "get"
    - path: "https://hastebin.up.railway.app"
      type: "get"
    - path: "https://glitch247.aytea14.repl.co"
      type: "get"
    - path: "https://mycolorapi.glitch.me/2ed573.png"
      type: "get"
