name: Monitor

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.13.1"

            - name: 🛸 Check status
              run: cd src && npm install && npm run build && npm run start

            - name: ⌨️ Commit files
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name  "github-actions[bot]"
                  git add .
                  git commit -m "🗒️ Updated Summary"                  

            - name: 🚀 Push changes
              uses: https://github.com/ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.TOKEN }}
